image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy
 
maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - docker pull nginx
    - docker tag nginx dregistry:5000/nginx:v1
    - docker push dregistry:5000/nginx:v1

deploy:
  image: maven:3-jdk-8
  stage: deploy
  script:
    - ssh root@192.200.1.1
    - kubectl create -f nginx.yaml
    - kubectl expose deployment nginx

